version: '3.3'

services:
  nginx:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - app

  app:
    build: .
    env_file: .env
    restart: always
    depends_on:
      - db

  db:
    build: ./initdb
    env_file: .env
    restart: always
    volumes:
      - data:/data/db

volumes:
  data: