version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file: .env    
    depends_on:
      - db

  db:
    build: ./initdb
    env_file: .env
    restart: always
    volumes:
      - data:/data/db

volumes:
  data: