version: '3.3'

services:
  app:
    build: .
    env_file: .env
    ports:
      - target: "${PORT:-80}"
        published: "${PORT:-8080}"
    depends_on:
      - db

  db:
    build: ./initdb
    env_file: .env
    volumes:
      - data:/data/db

volumes:
  data: