version: '3'

services:
  app:
    build: .
    env_file: .env
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./initdb
    env_file: .env
    volumes:
      - data:/data/db

volumes:
  data: